#!/usr/bin/env python3
"""Build the CAPAG <-> CityCatalyst crosswalk and probe climate-data coverage.

1. Pull CityCatalyst's CCRA city list for BR (5,570 cities w/ locode + name + UF)
2. Match against data/capag.json on (normalized name, UF) -> data/crosswalk.json
3. Probe a stratified sample (per CAPAG tier) for SEEG emissions + CCRA risk
4. Emit research/coverage-report.md

Usage: python3 scripts/probe_citycatalyst.py [--sample-per-tier 4]
"""
import argparse
import json
import sys
import unicodedata
import urllib.parse
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path

API = "https://api.citycatalyst.io"
ROOT = Path(__file__).resolve().parent.parent
TIERS = ["A+", "A", "B+", "B", "C", "D", "n.d.", "n.e."]


def get_json(url, timeout=30):
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return json.load(r)
    except Exception as e:
        return {"_error": str(e)}


def norm(name: str) -> str:
    s = unicodedata.normalize("NFD", str(name))
    s = "".join(c for c in s if not unicodedata.combining(c))
    return "".join(c for c in s.lower() if c.isalnum())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sample-per-tier", type=int, default=4)
    args = ap.parse_args()

    capag = json.loads((ROOT / "data" / "capag.json").read_text())["records"]
    print(f"CAPAG records: {len(capag)}", file=sys.stderr)

    print("fetching CCRA BR city list...", file=sys.stderr)
    cc_cities = get_json(f"{API}/api/v0/ccra/city/BR", timeout=60)
    assert isinstance(cc_cities, list), cc_cities
    print(f"CityCatalyst BR cities: {len(cc_cities)}", file=sys.stderr)

    cc_index = {}
    dupes = set()
    for c in cc_cities:
        key = (norm(c["cityname"]), c["region"])
        if key in cc_index:
            dupes.add(key)
        cc_index[key] = c["actor_id"]

    matched, unmatched = [], []
    for m in capag:
        key = (norm(m["municipio"]), m["uf"])
        locode = cc_index.get(key)
        rec = {**m, "locode": locode, "ambiguous": key in dupes}
        (matched if locode else unmatched).append(rec)

    xwalk = ROOT / "data" / "crosswalk.json"
    xwalk.write_text(json.dumps({
        "matched": len(matched), "unmatched": len(unmatched),
        "ambiguous_keys": len(dupes), "records": matched,
        "unmatched_records": [
            {"cod_ibge": u["cod_ibge"], "municipio": u["municipio"], "uf": u["uf"], "capag": u["capag"]}
            for u in unmatched],
    }, ensure_ascii=False))
    print(f"matched {len(matched)} / {len(capag)} (ambiguous keys: {len(dupes)})", file=sys.stderr)

    by_tier = defaultdict(list)
    for m in matched:
        by_tier[m["capag"]].append(m)

    # stratified probe: SEEG (any of 2 sectors) + CCRA risk per sampled city
    probe_results = []
    for tier in TIERS:
        for city in by_tier.get(tier, [])[: args.sample_per_tier]:
            loc = urllib.parse.quote(city["locode"])
            seeg = get_json(f"{API}/api/v1/source/SEEGv2023/city/{loc}/2022/I.1.1")
            seeg_ok = isinstance(seeg, dict) and "totals" in seeg
            if not seeg_ok:
                seeg2 = get_json(f"{API}/api/v1/source/SEEGv2023/city/{loc}/2022/V.1")
                seeg_ok = isinstance(seeg2, dict) and "totals" in seeg2
            ccra = get_json(f"{API}/api/v0/ccra/risk_assessment/city/{loc}/current")
            ccra_ok = isinstance(ccra, list) and len(ccra) > 0
            probe_results.append({
                "municipio": city["municipio"], "uf": city["uf"], "capag": tier,
                "locode": city["locode"], "seeg": seeg_ok, "ccra": ccra_ok,
                "ccra_hazards": len(ccra) if ccra_ok else 0,
            })
            print(f"  {tier:4} {city['municipio'][:30]:30} seeg={seeg_ok} ccra={ccra_ok}", file=sys.stderr)

    (ROOT / "data" / "probe-results.json").write_text(json.dumps(probe_results, ensure_ascii=False, indent=1))

    # coverage report
    tier_counts = Counter(m["capag"] for m in capag)
    match_counts = Counter(m["capag"] for m in matched)
    lines = [
        "# CAPAG × CityCatalyst coverage report", "",
        "Generated by `scripts/probe_citycatalyst.py`. Join key: normalized (municipality name, UF)",
        "between Tesouro's CAPAG file and CityCatalyst's CCRA BR city list (which carries UN/LOCODEs).", "",
        f"- CAPAG municipalities: **{len(capag)}**",
        f"- CityCatalyst BR cities (CCRA list): **{len(cc_cities)}**",
        f"- Matched: **{len(matched)}** ({len(matched)/len(capag)*100:.1f}%) — unmatched: {len(unmatched)}",
        "", "## Match rate by CAPAG tier", "",
        "| Tier | Municipalities | Matched | % |", "|---|---|---|---|",
    ]
    for tier in TIERS:
        t, m = tier_counts.get(tier, 0), match_counts.get(tier, 0)
        if t:
            lines.append(f"| {tier} | {t} | {m} | {m/t*100:.1f}% |")
    ok_seeg = sum(1 for p in probe_results if p["seeg"])
    ok_ccra = sum(1 for p in probe_results if p["ccra"])
    lines += [
        "", f"## API probe (stratified sample, {args.sample_per_tier}/tier)", "",
        f"- SEEG emissions (2022): **{ok_seeg}/{len(probe_results)}**",
        f"- CCRA risk assessment (current scenario): **{ok_ccra}/{len(probe_results)}**",
        "", "| City | UF | CAPAG | LOCODE | SEEG | CCRA (hazards) |", "|---|---|---|---|---|---|",
    ]
    for p in probe_results:
        lines.append(
            f"| {p['municipio']} | {p['uf']} | {p['capag']} | {p['locode']} "
            f"| {'✅' if p['seeg'] else '❌'} | {'✅ (' + str(p['ccra_hazards']) + ')' if p['ccra'] else '❌'} |")
    lines += [
        "", "## Notes", "",
        "- CCRA endpoint: `GET /api/v0/ccra/risk_assessment/city/{locode}/{scenario}` — scenario segment is",
        "  required (current | pesimistic | optimistic); locode keeps its space, URL-encoded (`BR%20POA`).",
        "- The CCRA BR city list (`/api/v0/ccra/city/BR`) doubles as the IBGE↔LOCODE crosswalk source.",
        "- HIAP prioritized actions: per-city endpoints exist in global-api routes",
        "  (`actions_pathway.py`, `city_action_policy_scores.py`) — not probed yet.",
    ]
    out = ROOT / "research" / "coverage-report.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
